feat: add documentation
mineiros-io/terraform-kubernetes-role pull request #5
Opened 2022-02-15 06:43 UTC by kassianh

2022-02-28 16:05 UTC, soerenmartius approved these changes
lgtm

2022-02-28 16:06 UTC, soerenmartius requested changes, later dismissed

2022-02-28 16:06 UTC, soerenmartius commented on README.md
> +-https://kubernetes.io/docs/reference/access-authn-authz/authorization/
```suggestion
- https://kubernetes.io/docs/reference/access-authn-authz/authorization/
```

2022-03-30 23:35 UTC, mariux approved these changes
lgtm

2022-03-30 23:35 UTC, merged